#!groovy
@Library('utils') _

pipelineTriggersVar = []
if (env.BRANCH_NAME == 'develop') {
	pipelineTriggersVar << pipelineTriggers([cron('0 16 * * *')])
}

properties(
	pipelineTriggersVar
)

pipeline {
	options {
			// timeout job after 10 hrs
			timeout(time: 10, unit: 'HOURS')
	}

	agent {
		// run creation and post cleanup on anything that's 
		// env-dev
		label 'env-dev'
	}

	parameters {
		choice(choices: 'dev', name: 'TargetEnvironment', description: 'Environment to target')
	}

	environment {
		// these are not specifically needed for this jenkins job at the moment but could turn useful later
		AWS_ACCOUNT = sh(returnStdout: true, script: "aws sts get-caller-identity --output text --query 'Account'").trim()
		AWS_REGION = sh(returnStdout: true, script: "curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\\(.*\\)[a-z]/\\1/'").trim()
		SHORTCOMMIT = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()

		logDropFolder = "lens48/build_${env.BUILD_NUMBER}_${params.TargetEnvironment}"
		nexusRepository = "test-logs"
		testLogsFileName = "test_logs.zip"
		testScreenshotFileName = "screenshots.zip"
	}

	stages {
		stage('Activate Automation Slave') {
			steps {
				sh "aws autoscaling set-desired-capacity --auto-scaling-group-name jenkins-slave-testautomation-dev-ecs-2-JenkinsSlaveECSScalingGroup-1AKK7RRCFA0KP  --desired-capacity 1 --region us-east-1"
			    sleep 300 // this is in seconds so 5 minutes
			}
		}

		stage('Run Automated Test Suite') {
			agent {
				// agent is selenium-based but we need a few more requirements in it, so we use our own dockerfile
				// this requires SYS_ADMIN capability for chromium in the container (see https://github.com/jessfraz/dockerfiles/issues/65)
				docker {
                    image 'image'
                    args '--cap-add=SYS_ADMIN --shm-size 2GB'
                    label 'us-east-1 && env-dev && testautomation-power'
				}
			}
			steps {
				sh "./RunTestSuite.sh ${params.TargetEnvironment} ${env.BUILD_NUMBER} ${env.nexusRepository}:${env.logDropFolder} 'email@email.com'"

                script {
                  	if (fileExists("${env.testLogsFileName}")) {
                        nexus.publish(
                            type: 'raw',
                            env: 'prod',
                            credentials: nexus.getCredentials('us-east-1', 'prod'),
                            repository: "${env.nexusRepository}",
                            source_file: "${env.testLogsFileName}",
                            folder: "${env.logDropFolder}"
                        )
                    }
                }
                script {
                  	if (fileExists("${env.testScreenshotFileName}")) {
                        nexus.publish(
                            type: 'raw',
                            env: 'prod',
                            credentials: nexus.getCredentials('us-east-1', 'prod'),
                            repository: "${env.nexusRepository}",
                            source_file: "${env.testScreenshotFileName}",
                            folder: "${env.logDropFolder}"
                        )
                    }
                }
			}
		}
	}
	post {
			always {
				sh "aws autoscaling set-desired-capacity --auto-scaling-group-name tada  --desired-capacity 0 --region us-east-1"
			}
	}
}
