ASPXAUTH_COOKIE_NAME = ".ASPXAUTH"
ANTIFORGERY_COOKIE_NAME = "antiforgery"
REQUEST_HEADER_ANTIFORGERY = "anti-forgery-token"
REQUEST_HEADER_COOKIE = "Cookie"
SL_WRAP_COOKIE_NAME = 'STANDARDLIFEWRAP'
FNZ_COOKIE_NAME = 'FNZ'
TS_COOKIE_NAME = 'TS018e58fa'

# PLATFORM API CONSTANTS
PP_ACCOUNT_TYPE = 1
ISA_ACCOUNT_TYPE = 3
ACCOUNT_TYPE_INDIVIDUAL = 1
ACCOUNT_TYPE_JOINT = 2
ACCOUNT_TYPE_TRUST = 3


PATCH = "PATCH"
POST = "POST"

# API Test Results Query
TEST_OUTCOME_PASSED = "Passed"
TEST_OUTCOME_FAILED = "Failed"
TEST_OUTCOME_BLOCKED = "Blocked"
